package integrationtest.streamtest.generator


/**
  * Created by xiangnanren on 10/12/2016.
  */
object ProducerLauncher {
  def main(args: Array[String]): Unit = {
    //    if (args.length < 3) {
    //      System.err.println(
    //        s"""
    //           |Usage: <workLoad>
    //           |  <workLoad> concerns data size generated by stream generator
    //           |  <sleepDuration> is the interruption of data emission
    //           |  <generator type> is the type of stream generator
    //        """.stripMargin)
    //      System.exit(1)
    //    }

    val workLoad: Long = 70L
    val sleepDuration: Long = 2L
    val genType: String = "2"

    genType match {
      case "1" => Generator1(
        workLoad,
        sleepDuration
      ).generate()

      case "2" => Generator2(
        workLoad,
        sleepDuration
      ).generate()
    }
  }
}